services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    restart: unless-stopped
    ports:
      - "8096:8096"
    environment:
      - TZ:Europe/Madrid
    volumes:
      - jellyfin_config:/config
      - ./jellyfin_media:/media
    networks:
      - jellyfin_network

  caddy:
    image: caddy:latest
    container_name: caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    environment:
      - DOMAIN=${DOMAIN}
      - EMAIL=${EMAIL}
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - jellyfin_network

volumes:
  jellyfin_config:
  caddy_data:
  caddy_config:

networks:
  jellyfin_network:
    driver: bridge